Create database HospitaL

USE HospitaL
CREATE TABLE CITAS
(
FECHA varchar (50) NOT NULL,
PACIENTE varchar (50) NOT NULL,
HORA varchar (50) NOT NULL,
MEDICO varchar (50) NOT NULL,
CONSULTORIO varchar (50) NOT NULL,
EDAD int NOT NULL,
NP int NOT NULL,
)

CREATE TABLE GESTIÓN_DE_SALAS
(
SALA varchar (50) NOT NULL,
)

CREATE TABLE REGISTRO_DE_ACT
(
DIAGNÓSTICO varchar (50) NOT NULL,
)

CREATE TABLE REGISTRO_DE_PACIENTES
(
NP int NOT NULL,
)

CREATE TABLE SISTEMA_CONTABLE
(
NUMERO int NOT NULL,
)
